//-----------------------------------------------------------
// Generated with Kodeo's Reegenerator for NON-COMMERCIAL USE
//-----------------------------------------------------------

// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator
// Generator: Seasons
// Generation date: 2018-02-03 08:15
// Generated by: PC\gedda
// -------------------------------------------------------

    // Spring
    // Summer
    // Autumn
    // Winter

